### ISSUE TITLE
EasyPulse 1.3.0 New Features

### ISSUE THREAD

**Issue by p-chan5** [p-chan5/EasyPulse#8]
So I decided to make a tasklist for EasyPulse 1.3.0
At the moment there is no release date set but rest assured it will be out soon :)

* [ ] Expose new `Hold` setting in Compressor and Multiband Compressor effects, added in LSP [1.2.15](https://github.com/lsp-plugins/lsp-plugins/releases/tag/1.2.15). For more info check: https://github.com/wwmm/easyeffects/issues/2960.
* [ ] Follow new [Easy Effects Community Presets Guidelines](https://github.com/wwmm/easyeffects/blob/master/COMMUNITY_PRESETS_GUIDELINES.md). Also check: https://github.com/wwmm/easyeffects/issues/2445.
* [ ] Implement an experimental version (indie) of dynamic surround. For more info check: #4
* [ ] Publish two pre-built versions: One with low latency (default) and one with maximum latency; ideal for more demanding users.
